Repository jenkinsci/archetypes, pull requests merged in 2019-06, with the labels that each got.

#43 Move the changelog to GitHub releases, powered by Release Drafter
  .github/release-drafter.yml
  README.md
Labels: documentation

#42 [JENKINS-58040] make note about mirror limitation in settings.xml
  README.md
Labels: documentation

#45 Enable Dependabot for the repository
  .dependabot/config.yml
  pom.xml
Labels: internal

#63 Bump groovy-eclipse-compiler from 2.9.2-01 to 3.4.0-01
  global-shared-library/src/main/resources/archetype-resources/unit-tests/pom.xml
  scripted-pipeline/src/main/resources/archetype-resources/pom.xml
Labels: dependencies
