Repository jenkinsci/archetypes, pull requests merged in 2020-07, with the labels that each got.

#155 JENKINS-58557 Jenkins org archetype files
  README.md
  common-files/.dependabot/config.yml
  common-files/.github/CODEOWNERS
  common-files/.github/release-drafter.yml
  common-files/.github/workflows/release-drafter.yml
  common-files/.gitignore
  common-files/.mvn/extensions.xml
  common-files/.mvn/maven.config
  common-files/Jenkinsfile
  common-files/LICENSE.md
  common-files/README.md
  common-files/archetype-post-generate.groovy
  empty-plugin/pom.xml
  empty-plugin/src/main/resources/META-INF/maven/archetype-metadata.xml
  empty-plugin/src/main/resources/archetype-resources/pom.xml
  empty-plugin/src/test/resources/projects/testInstall/archetype.properties
  global-configuration/pom.xml
  global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml
  global-configuration/src/main/resources/archetype-resources/.gitignore
  global-configuration/src/main/resources/archetype-resources/pom.xml
  global-configuration/src/test/resources/projects/testInstall/archetype.properties
  global-shared-library/src/test/resources/projects/testInstall/archetype.properties
  hello-world/pom.xml
  hello-world/src/main/resources/META-INF/maven/archetype-metadata.xml
  hello-world/src/main/resources/archetype-resources/.gitignore
  hello-world/src/main/resources/archetype-resources/pom.xml
  hello-world/src/test/resources/projects/testInstall/archetype.properties
  scripted-pipeline/src/test/resources/projects/testInstall/archetype.properties
Labels: enhancement

#176 Use built in to GitHub dependabot
  .dependabot/config.yml
  .github/dependabot.yml
  common-files/.dependabot/config.yml
  common-files/.github/dependabot.yml
  common-files/archetype-post-generate.groovy
  pom.xml
Labels: chore

#177 Forgot to make license conditional for hello-world
  hello-world/src/main/resources/archetype-resources/pom.xml
Labels: bug

#178 Mistyped names of Incrementals profiles
  common-files/.mvn/maven.config
Labels: bug

#179 Section on Contributing was specific to @jenkinsci
  common-files/README.md
Labels: bug

#180 Set a defaultValue for hostOnJenkinsGitHub
  empty-plugin/src/main/resources/META-INF/maven/archetype-metadata.xml
  global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml
  hello-world/src/main/resources/META-INF/maven/archetype-metadata.xml
Labels: bug
