Repository jenkinsci/archetypes, pull requests merged in 2021-12, with the labels that each got.

#367 Adopt POM Code Convention
  empty-plugin/pom.xml
  empty-plugin/src/main/resources/archetype-resources/pom.xml
  global-configuration/pom.xml
  global-configuration/src/main/resources/archetype-resources/pom.xml
  hello-world/pom.xml
  hello-world/src/main/resources/archetype-resources/pom.xml
  pom.xml
Labels: chore

#366 Restore gitignore file to archetypes
  common-files/archetype-post-generate.groovy
  common-files/gitignore
Labels: bug

#371 Bump minimum version to recommended one
  empty-plugin/src/main/resources/archetype-resources/pom.xml
Labels: enhancement
