Repository jenkinsci/archetypes, pull requests merged in 2022-12, with the labels that each got.

#551 Remove linux 11 from CI testing by default
  common-files/Jenkinsfile
Labels: enhancement

#552 fix(buildPlugin pipeline library) Correct instruction to use Docker containerized tests
  common-files/Jenkinsfile
Labels: documentation

#568 Use proper path for dependabot common-files directory
  .github/dependabot.yml
Labels: chore
