Repository jenkinsci/archetypes, pull requests merged in 2023-08, with the labels that each got.

#651 Update default Jenkinsfile to include Java 21
  common-files/Jenkinsfile
Labels: enhancement

#654 Replace `org.kohsuke:pom` with `io.jenkins.tools:central-repository-pom`
  pom.xml
Labels: dependencies

#656 Use most recent release in example docs
  README.md
Labels: documentation
