Repository jenkinsci/archetypes, pull requests merged in 2023-03, with the labels that each got.

#597 Add Jenkins security scan to common files
  common-files/.github/workflows/jenkins-security-scan.yml
Labels: enhancement

#598 Use redirect URL
  common-files/.github/workflows/jenkins-security-scan.yml
Labels: documentation

#603 Switch to renovate for dependency management
  .github/dependabot.yml
  .github/renovate.json
  pom.xml
Labels: chore
